---
name: Main

on:
  workflow_dispatch:
    # this makes the workflow capable of being run manually

permissions:
  contents: write

jobs:
  run-release:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Upload Hello File to Release
        uses: rwaskiewicz/action-gh-release@0cf0a1da97158a8ccab7aae8ba6e6af8087f8e4c
        with:
          files: |
            *hello*
          draft: true
          tag_name: ${{ github.run_number }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_unmatched_files: true

      - name: "Append changelog"
        uses: softprops/action-gh-release@v2
        with:
          append_body: true
          body: |
            ## Changelog for ${{ github.run_number }}
            Some text
          tag_name: "${{ github.run_number }}"