---
name: Main

on:
  workflow_dispatch:
    # this makes the workflow capable of being run manually

permissions:
  contents: write

jobs:
  run-release:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Upload Hello File to Release
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2.2.1
        with:
          files: |
            *hello*
          draft: true
          tag_name: ${{ github.run_number }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_unmatched_files: true

      - name: Sleep
        run: sleep 5

      - name: Upload World File to Release
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2.2.1
        with:
          files: |
            *world*
          draft: true
          tag_name: ${{ github.run_number }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_unmatched_files: true

      - name: Create and Push Release Tag
        run: |
          git config user.name "versioning-tool"
          git config user.email "noop@gh.com"

          create_and_push_tag() {
            local tag="$1"
            local message="$2"
            echo "Creating tag: $tag"
            git tag -fa "$tag" -m "$message"
            git push origin "$tag" --force
          }
          create_and_push_tag "${{ github.run_number }}" "Release ${{ github.run_number }}"
