---
name: Main

on:
  workflow_dispatch:
    # this makes the workflow capable of being run manually

permissions:
  contents: write

jobs:
  run-release:
    runs-on: ubuntu-24.04
    steps:
      - name: Upload Hello File to Release
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2.2.1
        with:
          files: |
            "src/hello.js"
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_unmatched_files: true
      - name: Upload World File to Release
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2.2.1
        with:
          files: |
            "src/world.js"
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_unmatched_files: true
